name: dart_soccer_championship
description: A server app using the shelf package.
version: 1.0.0
homepage: http://www.example.com

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  appwrite: ^5.0.0
  args: ^2.3.1
  dotenv: ^4.0.1
  shelf: ^1.3.0
  shelf_router: ^1.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
