name: dart_soccer_championship
description: A server app using the shelf package.
version: 1.0.0
homepage: http://www.example.com

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.1
  dart_appwrite: ^5.0.1
  dotenv: ^4.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  jaguar_jwt: ^3.0.0
  logger: ^1.1.0
  shelf: ^1.3.0
  shelf_router: ^1.1.2

dev_dependencies:
  build_runner: ^2.1.11
  injectable_generator: ^1.5.3
  lints: ^2.0.0
  shelf_router_generator: ^1.0.2
  test: ^1.16.0
